### ISSUE TITLE
What is "."?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [joshsh/ripple#60]
Per wiki/Commands, "." applied to a list is the dequote operator. But I can also apply it to the number 3. If I apply it to a list, it prints the list. If I apply it to 3, it does not show the 3. Does "." mean something else for numbers? Is it defined for other kinds of things too?

**Comment by JeffreyBenjaminBrown** [comment]
It's even weirder! There are four possible expressions you can make out of a 3, a "cheese" and maybe a trailing dot. Three of them evaluate:

45)  "cheese" 3
  [1]  "cheese" 3
46)  "cheese" 3.
47)  3 "cheese"
  [1]  3 "cheese"

The last does not:

48)  3 "cheese".
net.fortytwo.ripple.RippleException: argument is not a key/value pair: 3

I looked for words like key and value in Wiki/Commands and didn't find it. Am I overlooking some other introductory document?

**Comment by joshsh** [comment]
See answer at:
    https://groups.google.com/forum/#!topic/semantic-synchrony/1ykJc4LpCC0
