### ISSUE TITLE
How are @-commands different from programs? Which way is up in the stack? Braces?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [joshsh/ripple#61]
In the documentation I only seem to find @-commands defined on their own lines, as in
 @prefix : <http://example.org/myPrograms#>
I never find them in sequence. Other commands, like add and mul, can chain together. 

Also @-commands always precede their arguments, whereas other programs must follow their arguments. Which makes me ask: which side of a string of text is the top of the stack?

Are those prefix @-commands macros? Can they be interlaced with the (ordinary?) postfix programs? Are there parentheses?

**Comment by joshsh** [comment]
See answer at:
    https://groups.google.com/forum/#!topic/semantic-synchrony/1ykJc4LpCC0
