### ISSUE TITLE
Is the tail of an @unlisted list accessible?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [joshsh/ripple#62]
I saw this in the docs (at wiki/commands):
1)  @list tmp: 1 2 3
2)  :tmp rdf:first.

  [1]  1

3)  @unlist tmp
4)  :tmp rdf:first.

5)  

Shortly thereafter, it says "The tail of the list (if any) remains intact". In the above example, is the remaining "2 3" accessible somehow?

**Comment by joshsh** [comment]
See answer at:
    https://groups.google.com/forum/#!topic/semantic-synchrony/1ykJc4LpCC0
